package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"back/domain/constant"
	"back/domain/entity"
	"back/infrastructure/repository"
	"back/infrastructure/request"
	"back/usecase"
	"context"
)

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, name string) (*entity.MutationResponse, error) {
	req := request.NewCreateGroupRequest(name)
	msgs, ok := req.Validate(r.Validator)
	if !ok {
		return &entity.MutationResponse{
			Success:  false,
			Messages: msgs,
		}, nil
	}

	authUser := ctx.Value(constant.AUTH_USER_KEY).(*entity.UserEntity)
	orm := r.Resolver.Orm

	createGroupUsecase := usecase.NewCreateGroupUsecase(
		repository.NewGroupRepository(orm),
		repository.NewPointRepository(orm),
		repository.NewTransactionRepository(orm),
	)
	_, err := createGroupUsecase.Execute(entity.GroupEntity{
		Name: name,
	}, authUser.ID)
	if err != nil {
		return &entity.MutationResponse{
			Success:  false,
			Messages: []string{err.Message},
		}, nil
	}

	return &entity.MutationResponse{
		Success:  true,
		Messages: []string{"グループを登録しました。"},
	}, nil
}
