// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

import (
	"time"
)

type AccessTokenEntity struct {
	ID        uint32    `json:"id"`
	UserID    uint32    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt time.Time `json:"deleted_at"`
}

type AuthResponse struct {
	AccessToken string   `json:"accessToken"`
	Success     bool     `json:"success"`
	Messages    []string `json:"messages"`
}

type GroupEntity struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	DeletedAt time.Time `json:"deletedAt"`
}

type Mutation struct {
}

type MutationResponse struct {
	Success  bool     `json:"success"`
	Messages []string `json:"messages"`
}

type PointEntity struct {
	UserID    uint32     `json:"userId"`
	GroupID   uint32     `json:"groupId"`
	Amount    int32      `json:"amount"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Query struct {
}

type UserEntity struct {
	ID          uint32 `json:"id"`
	Name        string `json:"name"`
	AccountCode string `json:"accountCode"`
	Password    string `json:"password"`
	ImageURL    string `json:"imageUrl"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	DeletedAt   string `json:"deletedAt"`
}
